wandb_version: 1

batch_size:
  value: 64
epochs:
  value: 50
grid_size:
  value: 2
hidden_dim:
  value: 16
learning_rate:
  value: 0.001
limit:
  value: 128
num_hidden:
  value: 2
spline_order:
  value: 2
