_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 106
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 106
            "3":
                - 2
                - 17
                - 23
                - 55
            "4": 3.12.5
            "5": 0.18.7
            "6": 4.45.1
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
batch_size:
    value: 16
epochs:
    value: 10
hidden_dim:
    value: 64
learning_rate:
    value: 0.001
limit:
    value: 128
num_hidden:
    value: 3
